### PR TITLE
set SONAR_SCANNER_OPTS to properly pass trust store location to sonar-scanner

### PR DESCRIPTION
**Pull request by andykrohg**

### CODE REVIEW

**Comment by itewk** [comment]
@andykrohg this shouldn't be needed if using the latest PSR thanks to https://github.com/ploigos/ploigos-step-runner/commit/ced0ac575b6ce59019e2658c56a5c661ebf6f684

**Review by itewk — CHANGES_REQUESTED** [review]
shouldn't be needed if using latest PSR

**Comment by snelson-rh** [comment]
Setting SONAR_SCANNER_OPTS in the jenkins library is necessary as PSR doesn't work with the `-Djavax.net.ssl.trustStore`, the trustStore doesn't get passed to java.

**Comment by itewk** [comment]
....moving convo to chat

**Comment by itewk** [comment]
discussed on chat. issue is the fix in PSR didn't work. need to fix PSR to set ENV rather then pass keystore via command line.

**Comment by itewk** [comment]
oepned https://github.com/ploigos/ploigos-step-runner/issues/123

**Pull request closed without merging**
