### PR TITLE
ploigosWorkflowExistingContainerImageScan - refactor to use latest PSR which doesn't need container tar files

### PR DESCRIPTION
**Pull request by itewk**
# purpose
with https://github.com/ploigos/ploigos-step-runner/pull/178 PSR no longer needs / takes container image tars for doing container scanning, can just take an arbitrary container image tag and sort the rest so update the `ploigosWorkflowExistingContainerImageScan` workflow for that.

# integration test

- [ ] image scan that passes - don't have any images that pass any compliance lists at the moment, will just have to trust me if the compliance passes, this works as expected
- [X] [image scan that fails](https://jenkins-jenkins.apps.tssc.rht-set.com/job/Existing%20Container%20Image%20Scan/23/)

# dependent on
* https://github.com/ploigos/ploigos-step-runner/pull/178
* ideally a new set of released container images with the updated PSR in them

### CODE REVIEW

**Comment by itewk** [comment]
@mertel-rh once this and associated PSR changes and updated containers all get released this is a simpler version of workflow you are using.

**Comment by dwinchell** [comment]
comment says integration tests failed, but fwiw code lgtm. it's great we were able to pull out so much non-psr jenkins implementation

**Comment by itewk** [comment]
> comment says integration tests failed, but fwiw code lgtm. it's great we were able to pull out so much non-psr jenkins implementation

pass / fail meant two different use cases of showing a passing workflow vs a failing one based on the container scan results, but i can't get a passing one cuz ubi wont pass any standard compliance scans right now without tailoring.

**Review by dwinchell — APPROVED** [review]

**Comment by dwinchell** [comment]
fair enough

**Pull request merged**
