### PR TITLE
NAPSSPO-597 - stop using jenkins credentials and use SOPS encrypted tssc-config instead

### PR DESCRIPTION
**Pull request by itewk**
* pipelineJava8 - refactor to use named parameters
    * pipelineJava8 - refactor parameters now that all "encrypted" information can be in tssc config
    * pipelineJava8 - put push image step after scan image steps
    * pipelineJava8 - create emptyDir kube volume for /home/tssc so that pgp keys can be shared

### CODE REVIEW

**Comment by itewk** [comment]
example pipeline: https://jenkins-jenkins.apps.tssc.rht-set.com/job/tssc-reference-app-quarkus-rest-json/job/feature%252FNAPSSPO-597/64/

**Comment by itewk** [comment]
another example pipeline after fixes from @HunterGerlach  https://jenkins-jenkins.apps.tssc.rht-set.com/job/tssc-reference-app-quarkus-rest-json/job/feature%252FNAPSSPO-597/66/console

**Review by HunterGerlach — APPROVED** [review]
Looks good!

**Comment by itewk** [comment]
working pipeline using latest tssc lib: https://jenkins-jenkins.apps.tssc.rht-set.com/job/tssc-reference-app-quarkus-rest-json/job/feature%252FNAPSSPO-597/88/

**Review by ppremru — APPROVED** [review]

**Pull request merged**
